### ISSUE TITLE
Some bezel packs not listed in downloader

### ISSUE THREAD

**Issue by aormond** [thebezelproject/BezelProject#13]
Just installed the script on my retropie system. The only bezel packs that are in the downloader menu are:
MAME
Atari5200
Atari7800
GCEVectrex
MasterSystem
MegaDrive
NES
Sega32x
SegaCD
SG-1000
SNES
SuperGrafx

The rest of them are missing (e.g. Atari2600, PSX). Are they supposed to be listed? Looking at the source of the script, it looks like maybe they're deliberately not listed in the downloader?

**Comment by CoinJunkie** [comment]
The "only" bezels?  That's thousands of custom bezels hahaha.  We're working on it, we're on PlayStation right now

**Comment by aormond** [comment]
No offense meant. I just wasn’t sure if they were supposed to be available or not.

**Comment by thebezelproject** [comment]
Periodically check and see what new packs have been done.

Or join our Facebook group The Bezel Project to keep up-to-date on current packs.
