### ISSUE TITLE
Include configs for MAME

### ISSUE THREAD

**Issue by johnodon** [thebezelproject/BezelProject#15]
Looks like the arcade configs are for FBA, MAME2003 and MAME2010 only.  Can MAME (current MAME version from experimental) be included also?

**Comment by Websteria** [comment]
Agreed. MAME 2003 (0.78) which was the directory being used was causing my overlays not to show up. By copying the .cfg files into MAME 2003 (0.78) it worked perfectly.

**Comment by thebezelproject** [comment]
The RetroPie installer script has now been updated with the new folder name.  Not sure when the RetroArch devs changed it.  They don't really communicate those changes out very well.
