### ISSUE TITLE
XU4 ORA Users

### ISSUE THREAD

**Issue by 6alileo** [thebezelproject/BezelProject#16]
Hey guys, nice work on the bezel project. We'd like to be able to use this script without forking.

For the Odroid XU4 guys who use the Odroid Retro Arena image, I think there is one change required in the code.

On line 128 references this path:
`cd "/home/pi/RetroPie/retropiemenu"`

Could you guys make an if statement of some sort? The ORA image is using the path of
`cd "/home/pigaming/RetroPie/retropiemenu"`

I think you guys can leverage the isPlatform variable to determine if its a Pi or an XU4. Please do consider looking into this. Thank you on behalf of the ORA community.

**Comment by darky2003** [comment]
hi, did you already got it working?
seems like the bezels are downloaded but aren't applied to the roms. 
can't find any answer online.

**Comment by 6alileo** [comment]
Hi there - Try updating the bezel script and reinstall the system bezel packs. ORA will have v1.5 soon which will have it pre installed. We just need to do more testing. Are you in our Discord? Join it and we could get you access to the beta. It would help the small team of testers we have.

________________________________

**Comment by darky2003** [comment]
Sounds good to me. 
yeah, i'm in the discord channel.
you can find me as lizzardking1986#6874
