### ISSUE TITLE
Support for Native Retroarch 

### ISSUE THREAD

**Issue by lefty420** [thebezelproject/BezelProject#17]
Awesome stuff this project is amazing. I was wondering if there were any plans to to offer support outside of the retropie eco-system.  Would be fantastic to have support for windows and Linux.

**Comment by thebezelproject** [comment]
Thank you! We're working on it, I'll keep you posted.

**Comment by thebezelproject** [comment]
A member of our Facebook has now created a Windows based installer for our bezel packs.  It's a different repo, but there ya go!
