### ISSUE TITLE
ToeJam and Earl Bezel Overlays Onto Transparent Area

### ISSUE THREAD

**Issue by Breadwinka** [thebezelproject/BezelProject#18]
You can see here the side with Toejam overlays on to the transparent area. https://github.com/thebezelproject/bezelproject-MegaDrive/blob/master/retroarch/overlay/GameBezels/Megadrive/ToeJam%20&%20Earl%20(World).png

![image](https://user-images.githubusercontent.com/13487931/45797456-96ad4980-bc73-11e8-8042-994d5f80e05a.png)

**Comment by thebezelproject** [comment]
Thanks for pointing that out, I'll clean it up
