### ISSUE TITLE
A few questions about a amazing project?

### ISSUE THREAD

**Issue by ratmandom** [thebezelproject/BezelProject#24]
Just wondering question:
Are you going to make this so you can download bezels to any retroarch on lets say the wii u? I need to learn this stuff and I will be good one day. Enough respect for this work!

Main question:
And would these bezels work on the wii u/any console if I download them separately?

Dumb talk from me:
I need to setup bezels on MAME4DROID because they are supported, I think I should be able to figure that one out.

One day I want to see all emulators supported with bezels like a standard, that will be a dream come true for me.

**Comment by slappymcphee** [comment]
This project is for Debian based linux distros (Mainly Rasbian for Raspberry Pi and then Ubuntu on XU4) and not for any other operating systems. I doubt that the dev team would even have the hardware resources required to port to anything else. This isn't a part of RetroArch. This injects the images into the required folders on as previously stated.

**Comment by thebezelproject** [comment]
As-is, the bezel project is strictly an "in our spare time" group devoted to making a lot of bezel PNG files.

We provide a Raspberry Pi/RetroPie based installer as well as a Windows based installer.  A Facebook group member also converts them for use within RocketLauncher.  Ninja2bseen's work can be downloaded from EmuMovies.

At this time, we are not pursuing further platforms to create installers for.  A few folks have taken our bezel packs and manually installed them on other devices, but they do that on their own builds.
