### ISSUE TITLE
Bezel Project with Rocket Launcher

### ISSUE THREAD

**Issue by metzger52099** [thebezelproject/BezelProject#26]
I'm having an issue with using Rocket launcher showing the bezels for Turbo Graphx 16 and Turbo Graphx 16cd.  (retroarch). They work running retroarch alone, but not with Rocket Launcher. All other bezels from your project work though which is weird. Just these 2 systems wont. Any ideas?

**Comment by thebezelproject** [comment]
The best person/place for RocketLauncher issues is ninja2bseen.  You can find him on Youtube or EmuMovies.

This repo is for the Raspberry Pi installer script.  Ninja2bseen has taken the various bezel packs and converted them for use with RocketLauncher.

Also join the facebook group as well ... he is an active member there.
