### ISSUE TITLE
Games Without Bezels Defaulting to Input_Overlay

### ISSUE THREAD

**Issue by ptwiv** [thebezelproject/BezelProject#27]
I am using the Windows version of the BezelProject, and I have replaced all of my SNES rom files with the NoIntro rom pack files, with Retroarch being my default emulator.  

While experimenting going through different games to confirm the correct Bezel is displayed, I noticed that for any rom I opened that did not have a Bezel (e.g.,  hacks, translations, prototypes, etc.), Retroarch was defaulting to use the Bezel for the game/rom I opened first.  When looking at the Retroarch.cfg file, I see that the "input_overlay" setting is set to the config file for the first game/rom I opened (e.g., input_overlay = ":\overlays/GameBezels/SNES/Chrono Trigger (USA).cfg").  I can save the Retroarch.cfg file removing everything in between the quotation marks (e.g., input_overlay = ""), and the next time I open a game with a defined Bezel the Retroarch config file is updated to use that game's Bezel by default.  

Is this a known bug, or a bug at all?  I would assume that for any game where there is no Bezel config file that Retroarch would default to using no Bezel at all, or to using the Bezel's for the platform/system (e.g., the default SNES Bezel).

**Edit: Please let me know if I need to move this to the Windows specific Issues area.

**Comment by atylmo** [comment]
I'm also having this issue but I'm using the script (on Ubuntu, however).

**Comment by atylmo** [comment]
@ptwiv Just found out that this can be worked around by turning off "Save configuration on exit" in the emulator(s) and redownloading the bezel packs. See here: https://retropie.org.uk/forum/post/54630. It should work regardless of platform.
