### ISSUE TITLE
TG16 and TG-CD Bezels no longer working

### ISSUE THREAD

**Issue by PixelJunkie4x4** [thebezelproject/BezelProject#30]
The TG16 and TG-CD bezels are no longer working with the exception of the console bezel (default).  This behavior exists with Retroarch 1.7.6 installed on TheRA (3.0) and Retropie... It appears the core name was changed from Mednafen PCE Fast with 1.7.6 of Retroarch.  

As a result, the folder containing the cfg files for the core needs to change from Mednafen PCE Fast to Beetle PCE Fast.  Folder is located at /configs/all/retroarch/config.

**Comment by thebezelproject** [comment]
Thanks for letting us know.

Retroarch has been renaming several of the folders lately ... which has caused us some head aches!

The updates have been performed and the new Beetle PCE Fast folder has now been added in.
