### ISSUE TITLE
How do I uninstall Bezel Project?

### ISSUE THREAD

**Issue by mchamps** [thebezelproject/BezelProject#31]
I have a build where I don't need Bezel Project. Is there an easy way to uninstall everything?

**Comment by mistermintsgh** [comment]
I want to know this too!

**Comment by thebezelproject** [comment]
Thanks for the suggestion.

The bezelproject.sh script has now been updated with an uninstall option. You'll need to perform an update script to pull down this latest version.

The README.md file has also been updated with uninstall information.  It has information on how to manually remove the installed files/folders as well.

**Comment by mistermintsgh** [comment]
@thebezelproject

When you say the script has been updated, has it?

I updated mine today to find the uninstall script but it's not there. What do I need to do/type in order to uninstall bezel project automatically?
