### ISSUE TITLE
Save Bezel to Game?

### ISSUE THREAD

**Issue by Garavar** [thebezelproject/BezelProject#32]
Stupid question, on one of my games the wrong generic bezel was assigned (it's vertical instead of Horizontal)

I open retroarch menu go to overly and change it, works fine but when I exit the game and come back it's back to vertical. How do I save it for good?

I tried "Save State" I tried save changes on Exit but it just goes back. What am I missing?

**Comment by thebezelproject** [comment]
You don't do a "Save State" .. instead you would do a "Save Game Override".

Make sure to only perform the "Save Game Override" .. and not a "Save Core Override".
