### ISSUE TITLE
1941 Bezel with 1941u.zip

### ISSUE THREAD

**Issue by coolspot18** [thebezelproject/BezelProject#37]
Hi all,

The bezels work great with my selected list of non-merged MAME roms, but one specific bezel is giving me trouble - 1941.

I'm using 1941u.zip ROM and when it loads up in MAME 0.213b, the bezel is corrupt. Also, if going into TAB -> MAME -> Video Options, the overlay options are duplicated (i.e. Full, Framed, etc. are repeated twice on the list!). If I manually select the second "Full" option, the bezel loads up fine.

1941u.zip for my small list of ROMs is the only one that displays this strange error.

If I delete the 1941u.lay file in the artwork folder, the bezel loads up correctly.

Do you think this is a problem with MAME, the Bezel Project, or my setup?

My MAME install is stock. I made sure the game doesn't have any .cfg overrides. 

Thanks.

**Comment by thebezelproject** [comment]
Can you provide which platform and architecture you are using, e.g. Retropie, Windows? If Windows, MAME under Retroarch, or native MAME? Can you also provide the contents of the 1941 lay file you are trying to use?

**Comment by coolspot18** [comment]
Windows 10, 64-bit, running MAME 0.213b standalone.

- 1941u.lay: https://pastebin.com/bQgMg8q1
- 1941.lay: https://pastebin.com/2TH7K19k

If I delete 1941u.lay, the bezel loads up correctly. With 1941u.lay in place, the bezel is corrupt (diagonal grey lines across the screen), the video options (tab-> video options), display 8 bezel options (each of the 4 options repeated twice). 

I tested about 10 - 20 other roms, and don't have this problem.

Thanks.

**Comment by thebezelproject** [comment]
Those lay files were not created by the project installer, so there isn't much I can do. Having said that, I have seen this being reported on different forums related to the latest MAME and lay files. I know the MAME devs made a few changes that are proving incompatible with pre-existing installs.

All I can recommend is find a setting in MAME that works for that games bezel(s), then save a cfg file for that game.

**Comment by coolspot18** [comment]
I used the Windows BezelProject installer - they were created after the installer finished it job.

I'll delete the artwork folder and re-run the installer, but pretty sure the same files will be recreated.

Could it be an issue with the Windows installer?

**Comment by thebezelproject** [comment]
Make sure you are using the newest Windows installer from out Github page.

**Comment by coolspot18** [comment]
I'm using Web Installer 1.5, I think it was released in April?

**Comment by thebezelproject** [comment]
No, that is the old one. Get the new V1.0 on the releases page. It was released this month.
https://github.com/thebezelproject/BezelProject-Windows

**Comment by coolspot18** [comment]
> No, that is the old one. Get the new V1.0 on the releases page. It was released this month.
> https://github.com/thebezelproject/BezelProject-Windows

Cool, I may have found a legitimate "bug", on the NSIS page it says:

Note: this installer is no longer being developed/updated. If you desire a Windows based installer, please use the one from **https://github.com/thebezelproject/BezelProject-Windows-NSIS**. <-- It redirects back to the archived page :-)

**Comment by thebezelproject** [comment]
Thanks for catching that issue with the old readme. I have updated the link.

**Comment by coolspot18** [comment]
The new installer worked! Bezel and lay files all fixed.

Thanks!
