### ISSUE TITLE
Atari Lynx bezel dimensions

### ISSUE THREAD

**Issue by bfollowell** [thebezelproject/BezelProject#40]
I've noticed that the Atari Lynx was added as a system bezel pack. One issue I've noticed is that the edges of the screen and some text is cut off. Either the bezels aren't sized quite correctly or the gameplay screen needs to be shrunk/adjusted. Can I change that? If so, how?

Thanks for this wonderful project! It adds so much to all the games!

**Comment by thebezelproject** [comment]
In the Retroarch video options, what aspect ratio are you using? Have you tried 'Core provided'?

**Comment by bfollowell** [comment]
I haven't even gone into any Retroarch options yet. Most of what I've adjusted for various reasons have been RetroPie options, so I'm sure I'm setup for whatever the default is. I'll google that and try to find where/how to see how I'm setup and adjust if necessary and see how that affects things.

Thanks.

**Comment by bfollowell** [comment]
OK, I'm not sure if I'm looking at per game settings or system wide settings. I loaded a game that I knew was cut off, Gauntlet: The Third Encounter for the Atari Lynx, and pressed Select-X on my controller to pull up the Retroarch menu. If I go to the Retroarch Main Menu and select the Video option, I see that the aspect ratio is set to Core Provided, which I'm assuming is the default.

**Comment by thebezelproject** [comment]
OK, that being the case, keep scrolling down in that same video menu and see if 'integer scale' is set to on/true. If not, try that.

**Comment by bfollowell** [comment]
OK, that was set to off, and turning it on fixed the issue, at least with that one game anyway.

Now, if I exit out and come back in, it's back to off, so obviously I need to find a way to save that change. How do I do that. Also, is this a blanket change that will affect everything, or is it just this one core, or this one game?

Thanks.

**Comment by thebezelproject** [comment]
You need to save a core override, or 'Save current Configuration' for Lynx after making the 'Integer Scale' change.

**Comment by bfollowell** [comment]
I found Save Current Configuration, but it keeps saying it failed when I try to save retroarch.cfg

**Comment by thebezelproject** [comment]
Try saving a core override. Should be at the bottom of the Quick menu.

**Comment by bfollowell** [comment]
OK, I finally located it. Thank you. That helped a lot. Now I'm working my way through my various systems and making those changes. Everything looks great now.
