### ISSUE TITLE
Not seeing all Arcade bezels

### ISSUE THREAD

**Issue by dennisv1982** [thebezelproject/BezelProject#41]
Hi there,

first of all, great project!! I can't wait to use it for my arcade build. I am running RetroPie on Ubuntu, I have installed according to your manual. Everything installs without a error, BUT.... on some games in the arcade (mame) one i dont see the bezels... ie:
The Simpsons
Turtles in time
Turtles

I am sure you have bezels for those, but i am a complete NOOB for retropie and Ubuntu... is it the filename? And if yes, how do i find out the correct file name?

thank in advance

**Comment by thebezelproject** [comment]
Issues like you describe generally are because your rom file names do not match the cfg file names in /opt/retropie/configs/all/retroarch/overlay/ArcadeBezels, or the directory names under /opt/retropie/configs/all/retroarch/config do not match the names expected by the core you are using for the platform. Which Retroarch core are you using for Arcade?

**Comment by dennisv1982** [comment]
Hi there, I don't know much about ubuntu so I have no idea how to find that directory... :(

The core I am using is lr-mame2003

**Comment by thebezelproject** [comment]
Did you originally install an image that contained everything, or did you download separate pieces and put things together? If you downloaded the MAME roms separate, which set did you download?

**Comment by dennisv1982** [comment]
I downloaded a set, the file name in the set is simps2pj.zip and i see the name in the directory as simpsons2pj.cfg. But if i change the file name to simpsons2pj.zip.. the game doesnt run and after trying to boot it up it goes back to the menu

**Comment by thebezelproject** [comment]
Don't rename the roms. Rename the cfg files under /opt/retropie/configs/all/retroarch/config/<core name>, where core name should be MAME 2003 (0.78) for the core you said you were using. If renaming the files in that directory does not work, try renaming in the MAME 2003 directory in that same config directory.

**Comment by dennisv1982** [comment]
I will try tomorrow! Where I live its time for bed now 😁 I will let you know. Thank you and have a good day

**Comment by dennisv1982** [comment]
Ok, i renamed one of the cfgs to the name of the rom in the (0.78) directory... now i have no bezel at all, just black :p
