### ISSUE TITLE
Installation Script hardcoded directory

### ISSUE THREAD

**Issue by ahmdsmir** [thebezelproject/BezelProject#42]
Hello,

I use EmulationStation on Linux, not on a RaspberryPi, and the installation is not under /home/pi/. The script here seems to have the "pi" or "pigaming" hardcoded. If I want to make this work for me, should I just edit the installation file to hardcode my own custom home directory or maybe it would make sense to make the script user-agnostic?

**Comment by thebezelproject** [comment]
I would just edit the script to match your installation.

**Comment by ahmdsmir** [comment]
@thebezelproject Roger that! Cheers!!
