### ISSUE TITLE
File name

### ISSUE THREAD

**Issue by Vojovnik** [thebezelproject/BezelProject#43]
Hey guys, hope you're well! I'm wondering if there's a way to make the bezel project search and set the borders for the closest match of the title? Cause my roms are all renamed like "Metroid.nes" without an "(USA") or something like that in it.

**Comment by thebezelproject** [comment]
Sorry, not possible as that is way outside the scope of the installers. As stated, we use the No-Intro naming standard as of the time of the bezel pack creation. You will need to use one of the many renaming utilities if your rom names do not match the bezels.
