### ISSUE TITLE
Raspberry Pi 4

### ISSUE THREAD

**Issue by mikeydoom** [thebezelproject/BezelProject#44]
The bezel project doesn't seem to work on retropie on my Raspberry Pi 4.

The script installs fine, and I can run it.

But when I go to install bezels it'll download them and process them but doesn't say they're installed and doesn't display them after launching the system I launch.

**Comment by mikeydoom** [comment]
Maybe the script has to be updated for the rpi 4?

**Comment by geoffoxholm** [comment]
Works on my Pi4. Could you give any more information about what's not working?

**Comment by motorheadmeyhem** [comment]
I am having the same issue, I did not see a fix, was there a solution? Any help would be appreciated.

**Comment by matteozel** [comment]
same issue for me (latest retro-pie, latest bazel script on pi4) but only for NGPC bezels. Every other system I've tried is working well

**Comment by thebezelproject** [comment]
No updates are required for the pi4. Make sure your OS is fully updated and your rom file names match the Bezel cfg file names.
