### ISSUE TITLE
Missing Bezels

### ISSUE THREAD

**Issue by mayorre** [thebezelproject/BezelProject#46]
Hello everybody

First of all, thanks for this excellent project.

I have been updating my retroarch but I can't find some bezels, I just made the missing bezels by my self but I would like to contribute with them. I am sorry if I am using the wrong way, I have been searching how to do it but I can't find the way to help or contact the owner of the project.

Please let me know and again, thank you very much.

Best Regards

**Comment by thebezelproject** [comment]
The easiest way to share is to archive all your files, then host them on Google Drive, Dropbox, or similar service. Then provide a download link here in the appropriate Github repo, along with an explanation of what they are for.
