### ISSUE TITLE
Install just game system bezels, not every game?

### ISSUE THREAD

**Issue by ecolman** [thebezelproject/BezelProject#47]
Appreciate all the hard work that has gone into this, it's an amazing project.

I have a small RetroPie image which I wanted to install some bezels on, but not for each game since that takes up so much space.  Is there an option to install only game system bezels and use that instead of each game?  I've searched around and went through the scripts' options, but can't find anything.  Thanks!

**Comment by thebezelproject** [comment]
There is no option in the script that does what you want, however you can download the default system bezels and associated cfg files directly from the Github repos. Look in the retroarch/overlay directories.
