### ISSUE TITLE
Suggestion: Bezel Mixture 

### ISSUE THREAD

**Issue by awesomecoder3000** [thebezelproject/BezelProject#49]
Use theme bezels for all available games, but use system bezels if a game does not have a theme bezel

**Comment by thebezelproject** [comment]
There are no plans to include this as an additional option since you can do that now. Install system bezels first, then themed which will overwrite any existing system bezels. This will give you what you suggest.

**Comment by awesomecoder3000** [comment]
Thanks, this is what I wanted
