### ISSUE TITLE
Sega Genesis

### ISSUE THREAD

**Issue by huffyX** [thebezelproject/BezelProject#51]
Love the project.

I was wondering if there is anyway if getting the blastem core from retroarch to work with BP. I love the controls that is associated with blastem core. 

I have tried the genesis plus gx which works with BP but my controller conif is all wonky for certain games.

**Comment by thebezelproject** [comment]
Sure, just copy the "Genesis Plus GX" directory located in the config directory to a directory called BlastEm. See if that works for you.

**Comment by huffyX** [comment]
Wow, this worked like a charm. Thank you so much.

I also tried this with N64 for the Mupen64Plus-Next core. Tried moving it from another core to the core that works for me. And there are no Bezels. Could you please guide me through this one as well please. Thanks again

**Comment by huffyX** [comment]
Actually I figured it out from another post. My Rom set has a different name than the one with the config file.
