### ISSUE TITLE
Install-Problems

### ISSUE THREAD

**Issue by rebornkid** [thebezelproject/BezelProject#52]
I installed the bezel project on my raspberry pie 4 model b. The system bezels works perfect, but i cant figure out how to install the theme bezels. When i start a game, going into the setup menu, overlays, and then select a theme bezel, override game, it works until i start up the game again. Then the game doesn't work properly, the ratio changed completely and its not possible to change it like it was before.
For testing, i just try for the sega 32x.
After the installation, i have following folders:
cofings/all/retroarch/overlay/Gamebezels/Sega32x => Bezels inside

Themebezels are in the Gamebezels-Folder

**Comment by thebezelproject** [comment]
To download Themed style bezels should be choice 3 on the main menu. System style should be choice 4. If you don't see these choices, make sure you perform an 'Update install script', choice 1.

Manual selections of bezels can be saved by performing a game override within the Retroarch menu system. For other Retroarch type questions, I recommend asking questions on the libretro forum section.
