### ISSUE TITLE
Super Pang (Europe) - SNES Style Bezel

### ISSUE THREAD

**Issue by Calvorejas** [thebezelproject/BezelProject#53]
Hi, I would like to have a bezel for Super Pang for SNES... But I noticed that there is currently no bezel for that game. I don't know if someone working on this project has already made one and it is still on hold before it gets added... Even if that's the case I created my own version of the bezel... The thing is that I don't know how to make it appear on the screen when I play the game... I add it to the GameBezels/SNES folder but nothing happens...

I hope that at least my bezel helps a bit...

Edit: BTW... I'm in the latest build of RetroPie for Raspberry Pi 4

![Super Pang (Europe)](https://user-images.githubusercontent.com/74108190/98943476-d8527b80-24ef-11eb-8adc-5aa4b1073f2b.png)

**Comment by thebezelproject** [comment]
Thank you for your contribution. I have added it to the SNES repo.

**Comment by Calvorejas** [comment]
Great! Glad I could help somehow 👍🏼
