### ISSUE TITLE
The Hunt for Red October (USA) - SNES Style Bezel

### ISSUE THREAD

**Issue by Calvorejas** [thebezelproject/BezelProject#54]
Hi, I recently posted an "issue" regarding the SNES Style Bezel for Super Pang... I would also like to contribute with this other game's Bezel... It may not be perfect but if it helps, I'm more than happy... That's my intention.

Hope this Bezel helps somehow.

![The Hunt for Red October (USA)](https://user-images.githubusercontent.com/74108190/98946348-10f45400-24f4-11eb-98d7-8e16b527fc00.png)

**Comment by thebezelproject** [comment]
Thank you for the submission, however we already have a bezel for this game. It is found using the No-Intro based name of Hunt for Red October, The (USA).

**Comment by Calvorejas** [comment]
Thank you, didn't noticed it... I had a bad ROM name.
Thanks for all your work, your bezels really make the difference while playing!
