### ISSUE TITLE
ArcadeBezels: Make bezel clones for 2 player patched ROMs please.

### ISSUE THREAD

**Issue by Calvorejas** [thebezelproject/BezelProject#55]
Hi, in my journey of creating my own arcade machine, The Bezel Project has been a great ally, but sometimes, not everything is perfect... I am experiencing some difficulties trying to get my 2 player patched ROMs to match The Bezel Project names... For example, I have the simpsons.zip ROM (I'm using both FBA and MAME) and that game is 4 player only... It makes it difficult to play when you only have two controls... The solution was to use a 2 player patched ROM, but the name is different for that ROM (it is "simpsons2p.zip") and because The Bezel Project doesn't expect that name it shows the generic "ARCADE" bezel...
Is there a possibility to add the same bezels for the normal ROMs to the 2 player patched ROMs?
For example... Is it possible to make a copy of "simpsons.png" (and also it's .cfg file, of course) and name it as "simpsons2p.png" so that the "simpsons2p.zip" ROM gets detected by The Bezel Project and the correct bezel shows up?
I am using as an example The Simpsons game, but there are a few other games that may require this small tweak such as Teenage Mutant Ninja Turtles (TMNT.zip) and Teenage Mutant Ninja Turtles - Turtles in Time (TMNT2.zip)... both 4 player games.
I'm sure there are more cases but for now, I'm not aware of them... 
It would be great if that change could be made as there is no luck for me when trying to rename the .zip files... That makes the games non-bootable and I could not find any way to rename them while still being able to launch them.
I hope that this does not suppouse any problem as it only would require a copy and rename of a few files (I guess).

Thanks in advance!

**Comment by thebezelproject** [comment]
Should be easy, and you only need to copy the cfg files under the directory that matches the core you are using under .../retroarch/config, I.e. FB Alpha, FinalBurn Neo, MAME, MAME 2003-Plus, MAME 2003 (0.78), MAME 2010.

Example: Copy simpsons.cfg to simpsons2p.cfg

No edits to the cfg file is necessary unless you want to use a different png file under .../retroarch/overlay/ArcadeBezels

**Comment by Calvorejas** [comment]
I'll try to do that, but whenever I try to add a new bezel manually, It always fails for me... From a bezel I know works fine, I copy the .cfg and the .png file and I rename them with the name of the ROM (I also edit the .cfg file changing the name of the .png file that the .cfg file is pointing at)... That procedure has never work for me as the generic bezel always shows up :( Is there anything I'm doing wrong? Thanks and sorry for being this annoying, I just want my DIY Arcade Mchine to be perfect.

**Comment by thebezelproject** [comment]
Read what I said again. Only copy the cfg files under the config directory, not the overlay directory.
