### ISSUE TITLE
contact needed 

### ISSUE THREAD

**Issue by Jmanning6600** [thebezelproject/BezelProject#57]
Sorry not sure where to post this but I'm currently working on Bezels for Atari lynx I would like to share them when I'm finished. If someone could point me in the right direction I would appreciate it.

**Comment by thebezelproject** [comment]
Leaving a message here is fine, however we already have Lynx bezels in both System art and Themed styles. Be glad to look at what you come up with, but can't promise we would use them.

We welcome people to join up to the Facebook group and participate when we kick off a new bezel set as we are always looking for people to help.

**Comment by Jmanning6600** [comment]
Hello and thank you for getting back to me.
My name is John Manning I've been a lead tester and co-founder of The Retro
Arena for some time now I do a lot of the graphics for them as well. I
really appreciate all you guys do for the community and would  like to give
back I didn't see lynx listed as a completed system but if its done already
then no need to do it again.  If there is Anything missing that I can work
on please let me know.

Thanks again.
John

**Comment by Jmanning6600** [comment]
![Dinolympics (USA, Europe)](https://user-images.githubusercontent.com/37354497/102003316-a04b7d80-3cd3-11eb-9b85-b1ced7a71cfc.png)
