### ISSUE TITLE
Bezel Project override configurations break RetroPie verbose logging 

### ISSUE THREAD

**Issue by busywait** [thebezelproject/BezelProject#58]
Found in RetroPie 4.7.1
Pi4B

The RetroArch configuration in RetroPie uses the config files in a particular way that is affected by the use of game override files. Installing the BezelProject game configurations has stopped the --verbose command-line option working correctly due to per-game override .cfg files.

- I have installed the BezelProject menu into RetroPi and used it to download a selection of System and Theme bezels.
- I have a ROM named Donkey Kong Country (USA).zip in RetroPie/roms/snes/
- When I run EmulationStation and run Donkey Kong Country I can choose to press a controller button to see the launch menu
- From the launch menu I chose "Run with verbose logging", allowed the game to start, and then quit the game

A log file is created, but it is much shorter than it should be, ending shortly after this line:
[Overrides] game-specific overrides found at /home/pi/.config/retroarch/config/Snes9x/Donkey Kong Country (USA).cfg

If I rename the override .cfg file then the verbose logging works correctly:
pi@rpi-tv:~ $ mv /opt/retropie/configs/all/retroarch/config/Snes9x/Donkey\ Kong\ Country\ \(USA\).cfg{,.bak}

I copied the configuration to a .zip.cfg in the RetroPie/roms/snes directory:
pi@rpi-tv:~ $ cp /opt/retropie/configs/all/retroarch/config/Snes9x/Donkey\ Kong\ Country\ \(USA\).cfg.bak ~/RetroPie/roms/snes/Donkey\ Kong\ Country\ \(USA\).zip.cfg

I added the required line to stop the game configuration overwriting the core or global configuration:
pi@rpi-tv:~ $ echo config_save_on_exit = "false" >> ~/RetroPie/roms/snes/Donkey\ Kong\ Country\ \(USA\).zip.cfg

Now I can start the game with the bezel, and also save a verbose log if needed.

This is discussed in the RetroPie forum:  [https://retropie.org.uk/forum/topic/28857/verbose-log-is-truncated-from-snes9x-with-super-mario-world](https://retropie.org.uk/forum/topic/28857/verbose-log-is-truncated-from-snes9x-with-super-mario-world)

My .zip.cfg contains this:

> input_overlay = "/opt/retropie/configs/all/retroarch/overlay/GameBezels/SNES/Donkey Kong Country (USA).cfg"
> 
> config_save_on_exit = false

**Comment by dmmarti** [comment]
Unfortunately, the Bezel Project does not support the use of the *.zip override files located in the /roms  folder like you manually created. (to do so would require significant re-work of everything).

As to this causing issues with verbose logging, that will be a bug with RetroArch itself.  There's a good chance this has been broken for a long time within RetroArch.

The same config files are used with RetroPie that are used within a Windows PC install as well.  I bet the Windows version has this same bug.

Reading your comments on the RetroPie forum, the Bezel Project script does not touch the /opt/retropie/configs/all/retroarch.cfg file.  It only touches the /opt/retropie/configs/(system)/retroarch.cfg files.  So I can't help with any changes you had in there.

**Comment by busywait** [comment]
Thx. Correct, Bezel Project did not touch my other config files, and they all work correctly. (I have everything working correctly now with the changes above, and am able to use the fantastic bezels - thank you for your work!)

The unfortunate side-effect of the game override files in your default install disabling the verbose logging capability in RetroArch is likely to cause frustration, but I understand your choice.
