### ISSUE TITLE
SNES smash TV bezel overlay 

### ISSUE THREAD

**Issue by soulrider911** [thebezelproject/BezelProject#59]
I noticed the overlay for super smash TV had an issue in the bottom left corner... a large black smudge of some kind most likely a photoshop/image issue of some kind I have attached an updated and resolved version:) 
![Super Smash T V  (USA)](https://user-images.githubusercontent.com/1074696/103101995-e60b1e80-45ce-11eb-8640-26a617116bae.png)

**Comment by thebezelproject** [comment]
Repo updated. Thanks!
