### ISSUE TITLE
EmulationStation Linux installation

### ISSUE THREAD

**Issue by archeart23** [thebezelproject/BezelProject#60]
been trying all day but cant find a way to get this to show up on settings on emulationstation..

like how batocera has it...

hope to get some info thanks!

**Comment by thebezelproject** [comment]
If following the installation info from the readme on Github doesn't work, all I can recommend is use a standard distro with full retropie/emulationstation support, and/or go to the Retropie docs site (https://retropie.org.uk/docs/Debian/) and follow the installation instructions for different linux distro types, then try installing the bezel shell script per the readme info here on Github.

For what it is worth, we have manually installed different distros per the Retropie instructions and installed our script with no issues, so it can be done, I.e. debian, etc.
