### ISSUE TITLE
EmulationStation Linux installation 2

### ISSUE THREAD

**Issue by archeart23** [thebezelproject/BezelProject#61]
Just for clarification when you said you have done it using retropie reference, was it done with retropie or with emulationstation standalone?

Sorry for double posting just want o clarify

**Comment by thebezelproject** [comment]
Sorry for not being clear. What I was referring to was having followed the official RetroPie docs under the 'Platforms' section of this page: https://retropie.org.uk/docs/

I personally have followed the Raspbian and Debian/Ubuntu sections to first get RetroPie/Emulationstation setup, then I installed the Bezel script using the steps from out readme.
