### ISSUE TITLE
launching bezelproject.sh causes black screen

### ISSUE THREAD

**Issue by loueyknew** [thebezelproject/BezelProject#64]
Seeing a weird thing and no other shell scripts from Emulationstation are doing this.  When i launch the bezelproject.sh from ES, i initially see the Bezel Project welcome screen, then my screen goes black, and obviously I cant see, so have to exit out with the ESC key.  Any thoughts?

**Comment by thebezelproject** [comment]
Have you tried reinstalling the Bezel Project script per the instructions on the Github page to see if that changes the behavior?

Are you running a standard build of Emulation Station on a Raspberry Pi?

**Comment by loueyknew** [comment]
Yes reinstalled per the instructions.  I'm running on RP4b and doing some testing on a dev build of ES (v2.10.0RP-DEV)  Its strange it's the only one that doesn't work.  It will work from SSH just not from ES.

**Comment by loueyknew** [comment]
ok think i found where the issue is.  In the first block of code for the title, etc below:
# Welcome
 dialog --backtitle "The Bezel Project" --title "The Bezel Project - Bezel Pack Utility" \
    --yesno "\nThe Bezel Project Bezel Utility menu.\n\nThis utility will provide a downloader for Retroarach system bezel packs to be used for various systems within RetroPie.\n\nThese bezel packs will only work if the ROMs you are using are named according to the No-Intro naming convention used by EmuMovies/Hyp$
    28 110 2>&1 > /dev/tty \
    || exit

If i comment that out, the screen doesn't flash and go black.  It goes right into the Menu....

**Comment by loueyknew** [comment]
any ideas how to fix besides commenting it out?

**Comment by loueyknew** [comment]
so very interesting, i changed the first block to this:

# Welcome
 dialog --backtitle "The Bezel Project" --title "The Bezel Project - Bezel Pack Utility" \
    --yesno "\nThe Bezel Project Bezel Utility menu.\n\nThis utility will provide a downloader for Retroarach system bezel packs to be used for various systems within RetroPie.\n\nDo you want to proceed?" \
    28 110 2>&1 > /dev/tty \
    || exit

And that worked.  So something between "within RetroPie" to the do you want to proceed is not liked....

**Comment by thebezelproject** [comment]
Not sure what is going on. I can't replicate the issue here on any machine I have. The only thing that comes to mind is some library in your OS installation is out of date. Try performing the following two commands on your Pi, then try things again:
sudo apt-get update
sudo apt-get upgrade

**Comment by loueyknew** [comment]
Ok will try that, its weird some txt is just not liked in that first block.  I know I could just remove that line and it will work, but wanted to find exactly the issue to let you know so if something needs to be fixed for future it can be.

**Comment by loueyknew** [comment]
Ok so think have it figured out.  Looks like the package "pcmanfm" is the issue.  So somewhere in the first code block of your awesome app, requires a specific version.  Very strange....  Only that first block too...  Anyways, I upgraded and now the menu is not blacking out after launching.  Hopefully this helps someone else down the road..  Thanks for the support and amazing app :-)  Great work.  Excited to keep seeing Bezel project future enhancements :-)  

Preparing to unpack .../pcmanfm_1.3.1-1+rpt26_armhf.deb ...
Unpacking pcmanfm (1.3.1-1+rpt26) over (1.3.1-1+rpt25) ...
Setting up pcmanfm (1.3.1-1+rpt26) ...
Processing triggers for mime-support (3.62) ...
Processing triggers for gnome-menus (3.31.4-3) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for desktop-file-utils (0.23-4) ..
