### ISSUE TITLE
Bezelproject won't load from the retropie menu. 

### ISSUE THREAD

**Issue by Troy1975** [thebezelproject/BezelProject#65]
I have installed the bezel project correctly. But when I reboot and go back into the menu and click it, it fades out to black and then just goes back to the retropie menu. Can anybody help? Seems to have something to do with using a USB drive for my  ROMs.

**Comment by thebezelproject** [comment]
Read over this thread and see if the fix there helps. https://github.com/thebezelproject/BezelProject/issues/64

**Comment by Troy1975** [comment]
Thank you very much but I sorted it last night. I appreciate the quick response though. Wow.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
