### ISSUE TITLE
Non-interactive mode

### ISSUE THREAD

**Issue by obrie** [thebezelproject/BezelProject#69]
Hi there -

I manage my RetroPie configurations entirely through non-interactive bash scripts.  Would you consider introducing a non-interactive mode such that this can be managed through CLI options?

For example, something along the lines of:

```bash
/home/pi/RetroPie/retropiemenu/bezelproject.sh install system nes
/home/pi/RetroPie/retropiemenu/bezelproject.sh install theme nes
...
```

Alternatively, it could be as simple as just being able to specify the bash function to call:

```bash
/home/pi/RetroPie/retropiemenu/bezelproject.sh install_bezel_packsa "..." "..."
```

The latter example isn't far different from how `~/RetroPie-Setup/retropie_packages.sh` works and would be far easier to implement.  If you're open to it, I'd be happy to create a PR.

Thanks for all your hard work!

**Comment by thebezelproject** [comment]
We have no plans to introduce changes for separate CLI options at this time, however I will add your request to the wish list.

**Comment by obrie** [comment]
Are you open to me contributing a PR for it to see what you think?
