### ISSUE TITLE
Daphne Overlay Option Missing

### ISSUE THREAD

**Issue by cr45hmurphy** [thebezelproject/BezelProject#70]
I've noticed that there an option for the Daphne overlay is not present in the install script.

I know that there are two BezelProject repos for these:

https://github.com/thebezelproject/bezelprojectSA-Daphne
https://github.com/thebezelproject/bezelproject-Daphne

I realize that I can install this manually, and that is fine. But, is this supposed to be missing from the install script?

**Comment by thebezelproject** [comment]
Daphne bezels are only supported under Retroarch on Windows at this time.

**Comment by cr45hmurphy** [comment]
> Daphne bezels are only supported under Retroarch on Windows at this time.

Was actually about to close this, as I discovered that there are no current stable RetroArch cores for Daphne. Since that is the case, overlays won't work. My apologies for cluttering up the Issues queue.
