### ISSUE TITLE
NES aspect_ratio_index

### ISSUE THREAD

**Issue by obrie** [thebezelproject/BezelProject#71]
Hi there -

I'm curious about the intent of the `aspect_ratio_index` override for NES:https://github.com/thebezelproject/BezelProject/blob/bd15225c6906d1d426d967a7204adb5b1ffc3bca/bezelproject.sh#L1116

I'm using the bezels on a 1080p TV and, while all other games are scaled appropriately within the bezels, I found that NES games had several pixels from the game on the left and right cut off.  After some amount of time searching on forums, I saw a [comment](https://www.reddit.com/r/RetroPie/comments/bjr3b4/bezel_project_sides_of_games_covered_up/) to enable `video_scale_integer`, but the results did not seem correct.  Below are examples of different configurations and their impact:

### 19:14 aspect

```
aspect_ratio_index = 16
video_force_aspect = "true"
video_aspect_ratio = "-1.000000"
```

![nes-bubblebobble-aspect_ratio_16](https://user-images.githubusercontent.com/6991/116876657-caea9400-abea-11eb-9917-cfc7a4c48c6a.png)

### Core provided

```
aspect_ratio_index = 21
video_force_aspect = "true"
video_aspect_ratio = "-1.000000"
```

![nes-bubblebobble-aspect_ratio_core](https://user-images.githubusercontent.com/6991/116876756-f79eab80-abea-11eb-90d6-61e2acdaced4.png)

### 4:3 aspect

```
aspect_ratio_index = 0
video_force_aspect = "true"
video_aspect_ratio = "-1.000000"
```

![nes-bubblebobble-aspect_ratio_0](https://user-images.githubusercontent.com/6991/116876787-008f7d00-abeb-11eb-8cf6-760cbd4e390f.png)

### No overrides

```
# aspect_ratio_index = 16
# video_force_aspect = "true"
# video_aspect_ratio = "-1.000000"
```

![nes-bubblebobble-aspect_ratio_defaults](https://user-images.githubusercontent.com/6991/116877049-6976f500-abeb-11eb-8192-3d1ba66e8794.png)

### video_scale_integer

```
aspect_ratio_index = 16
video_scale_integer = true
```

![nes-bubblebobble-video_scale_integer](https://user-images.githubusercontent.com/6991/116877095-7a276b00-abeb-11eb-9661-ed29fc02dd9c.png)

## Thoughts

From the screenshots, it seems like `aspsect_ratio_index = 21` is perhaps the most accurate in terms of reflecting the original intent of the game, but `aspect_ratio_index = 0` seems most aesthetically pleasing in terms of being full-screen.

## Configuration

I have no overrides in `/opt/retropie/configs/all/retroarch.cfg`.

`/opt/retropie/configs/nes/retroarch.cfg`:
```
input_overlay = "/opt/retropie/configs/all/retroarch/overlay/Nintendo-Entertainment-System.cfg"
input_overlay_opacity = "1.000000"
aspect_ratio_index = "16"
video_force_aspect = "true"
video_aspect_ratio = "-1.000000"

input_remapping_directory = "/opt/retropie/configs/nes/"
run_ahead_enabled = "true"
run_ahead_frames = "1"
run_ahead_secondary_instance = "true"

#include "/opt/retropie/configs/all/retroarch.cfg"
```

FCEUmm core options:

```
fceumm_apu_1 = "enabled"
fceumm_apu_2 = "enabled"
fceumm_apu_3 = "enabled"
fceumm_apu_4 = "enabled"
fceumm_apu_5 = "enabled"
fceumm_aspect = "8:7 PAR"
fceumm_nospritelimit = "enabled"
fceumm_ntsc_filter = "disabled"
fceumm_overclocking = "disabled"
fceumm_overscan_h = "disabled"
fceumm_overscan_v = "enabled"
fceumm_palette = "default"
fceumm_ramstate = "fill $ff"
fceumm_region = "Auto"
fceumm_show_adv_sound_options = "disabled"
fceumm_show_adv_system_options = "enabled"
fceumm_show_crosshair = "enabled"
fceumm_sndquality = "High"
fceumm_sndvolume = "7"
fceumm_swapduty = "disabled"
fceumm_turbo_delay = "3"
fceumm_turbo_enable = "None"
fceumm_up_down_allowed = "disabled"
fceumm_zapper_mode = "lightgun"
fceumm_zapper_tolerance = "6"
```

## System information

* Raspberry Pi 4 Model B
* Raspbian Buster
* RetroPie 4.7.1
* Retroarch 1.8.8 (svn eb87c5e)
* lr-fceumm (latest)
* Sony KDL-40Z5100 (40" 1080p via HDMI)

**Comment by thebezelproject** [comment]
The NES bezels were created to support 4:3 aspect ratio. Some games have more pixels than others (up to the programmer, at the time) toward the edges, so many will appear cut off. You can also sometimes see a difference between PAL games and NTSC versions.

**Comment by obrie** [comment]
Thanks for the follow-up.  Just so I can understand -- since the bezels were created to support 4:3 aspect ratio, why does the index get set to `16` for a 19:14 aspect ratio?

**Comment by thebezelproject** [comment]
16 was correct for an older version of Retroarch, and when the bezels were created. The Libreto devs change the index numbers over time as needed. Feel free to update that number assuming you are on a newer version of Retroarch.

**Comment by obrie** [comment]
Ah hah, I think you're right there.  It looks like 16 is 19:12 on Retroarch 1.8.8 whereas 16 was 19:14 when the bezels were created.  I'll test that out tonight.  Thanks!

**Comment by obrie** [comment]
After updating the index to 17, this now works as expected.  Thanks!
