### ISSUE TITLE
Does bezel project on Retropie x86?

### ISSUE THREAD

**Issue by brandflake11** [thebezelproject/BezelProject#74]
Hello,
I'm running retropie on a 64-bit laptop on top of Lubuntu. Does bezel project work okay on x86 machines, or should I stay away from using this script? I don't want to destroy any configuration that is setup correctly. I don't see any mention of x86 retropie in the documentation of the bezel project.

Thank you very much for your help!

**Comment by thebezelproject** [comment]
You should be safe to follow the standard install steps found on Github. I run tests on an x86 Ubuntu based install myself. So far I haven't encountered any issues.

**Comment by brandflake11** [comment]
Thanks so much for the help. I would like to also suggest that the main README includes that it works on retropie x86, as it might make it easier for others in the future.
