### ISSUE TITLE
Bezels with Regions (USA) (Europe) (Japan) (Germany)

### ISSUE THREAD

**Issue by Mitch187** [thebezelproject/BezelProject#75]
Hi,

is it possible to add an feature, that we can use bezels from the usa-version to europe-version, japanese-versions or german-version?

An example:
I have a sega saturn rom: Andretti Racing (Germany).chd Andretti Racing (Europe).chd and i wan't that it out of the box works with your Andretti Racing (USA).cfg/png. Perhaps with symlinks or something, that we don't need double or triple version of the same .cfg/png files. But if necessary, it is ok.

Best Regards,
Mitch

**Comment by thebezelproject** [comment]
Unfortunately using soft links with Git repositories across different operating systems and different file system types can cause issues which the project is not currently able to support. Having copies is the only way at the moment.
