### ISSUE TITLE
Feature request - "tv frame" as separate image/layer

### ISSUE THREAD

**Issue by ReenigneArcher** [thebezelproject/BezelProject#76]
RetroArch overlays can contain multiple images. In my opinion the bezel project would be greatly improved IF the center section could be easily changed out for different styles of a TV frame.

I understand that the project is going for a CRT type of look, but personally I prefer a more modern looking frame. Maybe others prefer a more classic look even than the black CRT frame.

I know there are a lot of images and would probably require an automated script to remove the frame from each one. I would be happy to assist with this if you don't hate my idea.

**Comment by thebezelproject** [comment]
What we normally do is recommend batch processing the files to remove the tv frame if you don't like it. There are numerous apps that can do this.
