### ISSUE TITLE
How to install the bezel proyect in a standar retroarch linux (ubuntu) instalation on a desktop.

### ISSUE THREAD

**Issue by M3t4ll1k0** [thebezelproject/BezelProject#77]
The stript for using with retropie does not work if runed from a linux terminal (i assume it has to rum from retropies menu), there is a instaler for windows, but how can be this installed on linux to install the bezels on a regular desktop retroarch installation?
If you have a script that run in retropie it shouldn't be dificult to adapt it to run on a standard linux distro, no?

**Comment by thebezelproject** [comment]
I need more info that it does not work. Screenshots of the output, error message(s), etc.

Having said that, after following the steps here: https://retropie.org.uk/docs/Debian/, I have configured numerous desktop Linux installs of both Retropie and the Bezel Project script with no issue, so it is possible.

**Comment by M3t4ll1k0** [comment]
so i need to install retropie and execute the scrip from its menu? cnat be done using only retroach?

**Comment by M3t4ll1k0** [comment]
im installing retropie, but seems its going to install its how version of retroarch with its how paths.... i suppose i could manually copy al overlays to my actual retroarch installation and configure my retroarch installation manually to use the overlays, game by game. I'm writhe with this? then uninstall retropie and its own retroarch? I thik i would be rad if you just make and script to directlly install on regular retroarch in linux like you did on windows.

**Comment by M3t4ll1k0** [comment]
Ok i instaled retropie, it creates its own retro-arch installation under /opt/retropie/configs/all/retroarch but ironically the path or retroarch on retropies menu point to the local retroarch instalation ~.config/retroach .
I was expecing somthing like this to happen and i backed up my retroarch installation to a safe directory. and pinted in retropies retroach configuration the paths i configured myself pointing all what your script will do to my actual retroarch instalation and custom paths. (again i already backed up al that may be overwritten).
I executed your scrip from retropies menu and installed al bezel overlays. Then i launch my local retroarch installation.
Firs i was amazed about your great work and how lots of games loaded its bezel, but more than half of then didn't.
Then the next thing i noticed is that slang shaders disappeared, tried to download from my retroach meno online donloaderd but didn't work, luckily i backed up my retroarch original install and just copy the shaders folder to the actual modified retroarch instalation. That solved that problem. But lots of games like dreamcast for example that i have previuslly tweked its config both for some games and a global core and diretory opt dis show or din't show the bezels but they glitched, tried to just to delete all core directory and game opt and cfg files but some worked again some are still glitched.
Also all mame games chased when i try to load, i deleted al opt and cfg files for mame on config directory and im rescaning the mame roms folders to see if it solves the problem. Its still scaning them.
Also i discovered why most games does not load up bezel overlays by default all game and core cfgs into config have the option input_overlay =  pointing to /opt/retropie/configs/all/retroarch/overlay/ but the script since retropies retroarch used my actual overlay path (besides any other path) tour amazing bezels overlays are tried to be loaded from a empty retropies retroach directory, that's why loading them manually worked.
So what im going to do is while mantaining my retroarch paths create a symbolic link from my local RA overlays folder to /opt/retropie/configs/all/retroarch/overlay/ after uninstalling retropies and its retroarch and deleting all content of that folder but the link to overlays, if by any other fucked up shit any of my retroarch folders need to be ther couse any of your cfgs is pointing to there i will have the folder ready to create symbolic links. (a simbolic link is almost the same as coping a file or folder tho the path you create the link). So that sould solve it.
I will test it and read any config file or anything that has been changed in my retroarch instalation, and will report any bugs and how i managed to fix them (if i manage to).
Kudos for the impresing work with all the bezel overlay, amazing proyect. But really really users that what to use it on a normal retroarch installation on a linux desktop could really use a custom script that rums from a terminal and point to the correct paths and puts the correct files on the correct folders and that does not broke things on its retro arch installation.
Will come back and report if i aencounter any more issues or fixes.

**Comment by M3t4ll1k0** [comment]
well it seem that uninstalling retropie besides deleting his how retroach instillation also deleted my ~./config/retroach folder :/ i have a backup before your scrip installed his things specially cfgs and also backed up overlays folder after your scrip loaded there the goodies. At least i can come back to my impolute tweaked retroarch installation, but unless the retropie retroacrch folder i also backed up as the cgs, i think i will have to star over or just manually load the bezel overlays for each game, witch is not so bad.
Anyway, a script aimed to install your amazing project on a regular retroarch installation in linux like you have done for windows users would be amazing.

**Comment by M3t4ll1k0** [comment]
Final report:
After dumping my original ~./config/retroarch instalation doing that symbolic link groundwork and dumping the retropies retroarch /opt installation (that somehow seem to have been merged with my local one) config folder, all runs perfectly, nothing is broken now, all games load its bezel overlays automatically and i could not be more happy and grateful for your protect.
Only thing its now working as supposed to its that the overlay menu for every game options auto scale overlay and overlay opacity are in its default values and had to be tuned for each game, a minor issue.

PD: is you finally decide to make a script for common retroarch on linux like you did on windows, i'm not developer so i cnat assist you directly but if you need someone to beta test, and help you debug it i will be my pleasure.
