### ISSUE TITLE
Intellivsion Bezels installed, but not show in game

### ISSUE THREAD

**Issue by Mitch187** [thebezelproject/BezelProject#78]
Hi,

i have a retropie /retroarch installation and all other bezels for other systems works out of the box, when i use retroarch.
But the Intellivsion does not work. 

Greets
Mitch

the retroarch.cfg shows like the other systems:

`# Settings made here will only override settings in the global retroarch.cfg if placed above the #include line
input_overlay = "/opt/retropie/configs/all/retroarch/overlay/Intellivision.cfg"
input_overlay_opacity = "1.000000"

input_remapping_directory = "/opt/retropie/configs/intellivision/"

#include "/opt/retropie/configs/all/retroarch.cfg"       `

EDIT: i  found the problem: the config-file with the standard bezel is Mattel-Intellivision.cfg
Can you fix the problem in script?

**Comment by thebezelproject** [comment]
I have renamed the default bezel and updated the Github repos. Thanks!
