### ISSUE TITLE
NES game bezel PNG files missing

### ISSUE THREAD

**Issue by MatthiasStockert** [thebezelproject/BezelProject#8]
In the /opt/configs/all/retroarch/overlay/Game Bezels/NES folder a lot of png files are missing (starting at "Mega Man (USA)". They are also missing online: https://github.com/thebezelproject/bezelproject-NES/tree/master/retroarch/overlay/GameBezels/NES

**Comment by MatthiasStockert** [comment]
You see, the problem is not that there are no bezels for many games. The problem is that the cfg files are there (pointing to non existing png images), and thus you get only black borders and not even the standard system bezel.

**Comment by thebezelproject** [comment]
This should be corrected now.  Missing PNG files have been uploaded.
