### ISSUE TITLE
[REQUEST] Symbolic Links rather than multiple copies of same files

### ISSUE THREAD

**Issue by paulhlee1967** [thebezelproject/BezelProject#82]
Rather than duplicating all of the files for the multiple emulators supporting one core, only copy over one set of files, and use symbolic links for the remaining cores.

**Comment by thebezelproject** [comment]
Can't use symbolic links reliably for files in Github repositories in the manner we use the repos. We also use the repos on Windows, so any symbolic links would fail. Have tested this suggestion numerous times in the past and it isn't feasible at the moment, for more and varied reasons. Thanks for the suggestion.
