### ISSUE TITLE
Provide a package with all system only bezels

### ISSUE THREAD

**Issue by SuperPat45** [thebezelproject/BezelProject#86]
Can you provide a package containing a single bezel for each system?

I don't want to download hundreads of archives just to keep only a single bezel of each.

**Comment by thebezelproject** [comment]
The individual, default bezel for each system is available for direct download by visiting each repository and drilling down to the GameBezels directory.

**Comment by SuperPat45** [comment]
My question was precisely to avoid having to visiting a hundred repositories...

**Comment by thebezelproject** [comment]
What platform are you using? Windows or Pi?

**Comment by thebezelproject** [comment]
Attached is a PowerShell script that will download the default bezels for all current systems (Extract and save it to where you want to download the files, then right-click and select 'Run with Powershell'. We also recommend the bezel packs hosted on the Retroarch Github page: [https://github.com/libretro/overlay-borders](url)
[get_defbezels.zip](https://github.com/thebezelproject/BezelProject/files/8966098/get_defbezels.zip)

**Comment by SuperPat45** [comment]
Thank you very much!
