### ISSUE TITLE
Sega 32X SA and non-SA bezels have different sizes

### ISSUE THREAD

**Issue by X1pheR** [thebezelproject/BezelProject#87]
I have an issue where some games show a little behind the bezels. I use a fresh install of LaunchBox with RetroArch and its integrated Bezel Project downloader. RetroArch uses PicoDrive core and aspect ratio is set at as provided by core. It appears it has downloaded bezels from both repo's. So bezelproject-Sega32X and bezelprojectSA-Sega32X. The problem seems that the bezelprojectSA-Sega32X ones have bigger bezels which go over the game screen. Shouldn't they be the same width as the other one?

BTW, what does SA stand for? System Art?

https://github.com/thebezelproject/bezelproject-Sega32X
https://github.com/thebezelproject/bezelprojectSA-Sega32X

**Comment by thebezelproject** [comment]
Yes, both should be the same. bezelproject-Sega32X has been reworked to have the same aspect ratio as the others, 4:3.

SA does indeed stand for System Art.

**Comment by X1pheR** [comment]
Wow! that was fast. Thanks!

**Comment by X1pheR** [comment]
@thebezelproject Oh I noticed the default overlay hasn't changed so it's still in the wrong size
