### ISSUE TITLE
Not properly cleaned transparency for DOS games overlay?

### ISSUE THREAD

**Issue by RaptorZX4** [thebezelproject/BezelProject#89]
I found that when i use TheBezelProject overlay for the DOS games (in Batocera), there seem to be a badly-cropped image that shows outlines over the game, on the lower left. 
I think it may be the mouse picture that have transparency problem, or just not properly cleaned on the sides. When i use regular overlay, this problem doesn't happen.
I know this is a problem that could happen, a minor one, but since it's going over the games, i'll be using regular overlays in the meantime.

**Comment by thebezelproject** [comment]
Thanks for the report. A new release for Themed MS-DOS bezels is forthcoming. The System Art bezels will be updated per your report after that.

**Comment by thebezelproject** [comment]
The System Art bezels have been regenerated to remove the ghost rectangle. Thanks for reporting this.
