### ISSUE TITLE
m3u file support

### ISSUE THREAD

**Issue by goldengoat81** [thebezelproject/BezelProject#91]
sega cd has support for m3u files without the disc number

**Comment by thebezelproject** [comment]
What is the question? We support official naming conventions from the redump.org web site for systems with optical media, like the Mega/Sega CD. We don't currently support optional file naming like using m3u files.

**Comment by goldengoat81** [comment]
for your psx games that are multi disc you have an image for each disc as well as one for without a disc number final fantasy VII for example. if its something that is not supported then i can just change my m3u's to have disc numbers in them. thank you for writing me back so quickly. i do enjoy your bezels.
