### ISSUE TITLE
Titles mis-matched with No-Intro Names

### ISSUE THREAD

**Issue by ghost** [thebezelproject/BezelProject#92]
I'm sorry if this is the wrong place for this, but I'm noticing an issue. 

I ROMs from a no-intro romset, using what I think is the latest naming convention, but I'm finding a lot of bezels that are mismatched and not showing up in retroarch unless I go in and manually change the titles. I was wondering if you had any fixes or if there is some other naming list/convention that should be being used in order for the titles to match up. Cheers and thanks for your work!

**Comment by mrmadcatz** [comment]
My Retropie only has ~50 of each console I run, but each one had several mismatched names. These included gb, gba, gbc, nes, snes, megadrive. 

From what I can tell, there are a lot of region info mismatches. Lots of instances of (Japan, USA) (En) v. (USA). A big one I noticed is games like "Sonic the Hedgehog" being called "Sonic The Hedgehog" (and it's sequels) on no-intro site.

**Comment by thebezelproject** [comment]
Now that the backlog of new bezel packs for all the original systems requested systems have been completed, all the old repositories will be revisited. Missing bezels will be created and any naming errors will be address using the then current databases from No-Intro, Redump and TOSEC as needed.
