### ISSUE TITLE
cant use bezels for certain games using picodrive 

### ISSUE THREAD

**Issue by joonboi** [thebezelproject/BezelProject#94]
problem is that the games are named the same for different systems, and all use the same core. examples are Sonic the hedgehog for Sega Master system, Game Gear, and Genesis.  the three have different bezels, but setting one, overwrite the others because they all share the same name, and the bezel config per game is saved using the game name.

**Comment by thebezelproject** [comment]
That is one of the downsides of using a core that supports multiple systems. The easiest way around the problem you listed is to make the game/rom names different, then create a game override that points to a specific bezel that matches the bezel you want to be displayed.
