### ISSUE TITLE
Bug: BezelProject not showing

### ISSUE THREAD

**Issue by HarryC05** [thebezelproject/BezelProject#96]
I have installed this using the instructions in the readme, however, it is not showing in the retropie menu. 

When running the script while connected via ssh, I am greeted with the setup screen, however, when I press enter I am greeted with the following error:
```BASH
bezelproject.sh: 12: bezelproject.sh: Syntax error: "(" unexpected
```

Screen recording: https://drive.google.com/file/d/1Z4iSTiFmTMBJkWuVZO-1CoMKuviysMye/view?usp=sharing

**Comment by thebezelproject** [comment]
Does the script run from a terminal prompt?

**Comment by HarryC05** [comment]
Apologies if I am misunderstanding, do you mean by running the following?
```BASH
sh bezelproject.sh
```

**Comment by thebezelproject** [comment]
You can try that, or make sure you are in the directory where the script resides and try:
./bezelproject.sh

Also, are you running as the pi user?

**Comment by HarryC05** [comment]
ah, running
```BASH
./bezelproject.sh
```
seems to be working in the terminal, however, I am still not getting the option in the retropie menu.

**Comment by thebezelproject** [comment]
Although the script has worked for years from retropie, perhaps a recent change to retropie have caused this. Have you asked on the retropie forums if this is a known problem? We can't directly support Retropie issues, but we are very willing to make any edits that make things work once the change/mod is documented.

**Comment by HarryC05** [comment]
I have not, however, I will have a search around.

**Comment by thebezelproject** [comment]
Closing with no further response.
